### ISSUE TITLE
line limit

### ISSUE THREAD

**Issue by shaya0181** [i-make-robots/weaving_algorithm#4]
hi , in weaving _algorithm_circle i can't find a part to limit the number of lines without the work being left half-finished
there is  totalLinesToDraw=30000 but by lowering it to like 3000-4000 it just stops at line 3000 from 30000 line process. I hope you get what I mean

**Comment by i-make-robots** [comment]
Which one did you run?  There are three scripts.
I really appreciate that you use the issue system for an issue. That’s the best way.

**Comment by polemos0108** [comment]
i run weaving_algorithm_circle. but same problem. i choose 4000 lines to draw but it stopd at 2491.

**Comment by i-make-robots** [comment]
I have a modified version that writes all of them to a file. I haven’t checked it in yet because I broke other things.

**Comment by UnderConstruction-eng** [comment]
Hello. May I ask if you are using a canvas that is usually used in painting? Thank you

**Comment by i-make-robots** [comment]
There are several different versions of the algorithm in the repo.  Some use the canvas, some use an offscreen PImage buffer.

**Comment by UnderConstruction-eng** [comment]
Thank you for your reply sir. I appreciate it very much.
